config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'jobs#index'
  
  resources :jobs do
    collection do
      get :delete_all
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base

    helper_method :jobs_active

    def jobs_active
        @jobs = Job.where(deleted: :false)
    end
end

app/controllers/job_actions_controller.rb
class JobActionsController < ApplicationController

    def destroy
        byebug
        Job.destroy_all
    end

end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

require 'nokogiri'
require 'date'

class JobsController < ApplicationController
  def index
    @jobs = Job.all.order("date DESC")
  end

  def new
    if ScrapeLinkedin.new.perform
      redirect_to root_url
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to root_url
  end

  def delete_all
    Job.delete_all
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/job_actions_helper.rb
module JobActionsHelper
end

app/views/jobs/index.html.erb
<div id="typography" class="container mb-5">
    <div class="section-title col-xl-12 col-md-10 ml-auto mr-auto">
        <div class="example col-md-10 ml-auto mr-auto">
            <div class = "pt-5">
            
                <h3 style="text-align:left;"><%= image_tag("ror.png", :alt => "rss feed", size: "120x45") %><span style="float:right;"><%= @jobs.count%> jobs found </span></h3>
                <table class="table table-striped table-responsive-md" style="margin-top:30px;">
                    <thead class="thead-dark">
                        <tr>
                            <th style="text-align:center; width: 35%;">Job Title</th>
                            <th style="text-align:center; width: 30%;">Company</th>
                            <th style="text-align:center; white-space: nowrap; width: 15%;">List Date</th>
                            <th style="text-align:center; width: 10%;">Link</th>
                            <th style="text-align:center; width: 10%;">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @jobs.each do |job| %>
                            <tr>
                                <td>
                                <button type="button" class="btn btn-secondary btn-lg" data-toggle="modal" data-target="#myModal<%= job.id %>"><%= job.title %></button>

                                    <div class="modal fade bd-example-modal-lg" id="myModal<%= job.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                        <div class="modal-dialog modal-lg" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title" id="myModalLabel"><%= job.title %></h4>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                </div>
                                                <div class="modal-body">
                                                    <%= job.description.html_safe %>
                                                    <br><br>
                                                    <p>Job Post Date:
                                                    <%= job.date %></p>
                                                </div>
                                                <div class="modal-footer">
                                                    <h6>Link:<%= link_to image_tag("linkedin.png"), job.link, target: :_blank %></h6>
                                                    <h5><%= link_to 'Delete', job, class: "badge badge-danger ml-3", method: :delete, data: { confirm: "Are you sure?" } %></h5>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td style="text-align:center;">
                                    <h6><%= job.company %></h6>
                                </td>
                                <td style="text-align:center;">
                                    <h6><%= job.date %></h6>
                                </td>
                                <td style="text-align:center;">
                                    <h5><%= link_to image_tag("linkedin.png"), job.link, target: :_blank %></h5>
                                </td>
                                <td style="text-align:center;">
                                    <h5><%= link_to 'Delete', job, class: "badge badge-danger", method: :delete, data: { confirm: "Are you sure?" } %></h5>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
                <p style="text-align:center; margin-top:50px"><%= link_to 'Start New Search', new_job_path, class: "btn btn-warning"%>  |  <%= link_to 'Delete All', delete_all_jobs_path(@jobs) , class: "btn btn-danger"%></p>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Linkedinscraper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>